Update build workflow for ChromeOS ARCVM Kernel

diff --git a/.github/workflows/build-kernel-arcvm.yml b/.github/workflows/build-kernel-arcvm.yml
--- a/.github/workflows/build-kernel-arcvm.yml
+++ b/.github/workflows/build-kernel-arcvm.yml
@@ -1,122 +1,288 @@
-名称：构建内核 - ChromeOS ARCVM
-关于：
-  workflow_call：
-  workflow_dispatch：
+name: Build ChromeOS ARCVM Kernel
 
-环境：
-  git_tag： chromeos-5.10-arcvm
+on:
+  workflow_call:
+  workflow_dispatch:
 
-职位：
-  构建：
-    如果：github.event_name ！= 'pull_request' ||（github.event_name == 'pull_request' & ！github.event.pull_request.draft）
-    策略：
-      矩阵：
-        包括：
-          - ARCH：x86_64
-            kernel_image_name：bzImage
-            build_config：build.config.gki.x86_64
-            defconfig：x86_64_arcvm_defconfig
-          - 建筑：ARM64
-            kernel_image_name：图片
-            build_config： build.config.gki.aarch64
-            defconfig：arm64_arcvm_defconfig
+env:
+  git_tag: chromeos-5.10-arcvm
 
-    名称：构建 ChromeOS ARCVM 内核
-    运行时间：Ubuntu-22.04
-    环境：
-      LTO：薄弱
-      ROOT_DIR：/
-      KERNEL_DIR： ${{ github.workspace }}/kernel
+jobs:
 
-    步骤：
-      - 名称：安装构建工具
-        运行：|
-          Sudo APT获取更新
-          sudo apt-get install -y --no-install-recommends bc \
-          Bison Build-Essential CA-Certificates Flex Git GNUPG \
-          Libelf-dev libssl-dev LSB-release software-properties-common wget \
-          libncurses-dev binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu nuget gzip \
-          rsync python3 device-tree-compiler
-          sudo LN -s --force python3 /usr/bin/Python
-          导出 LLVM_VERSION=14
-          WGET https://apt.llvm.org/llvm.sh
-          chmod +x llvm.sh
-          sudo ./llvm.sh $LLVM_VERSION
-          rm ./llvm.sh
-          sudo LN -s --force /usr/bin/clang-$LLVM_VERSION /usr/bin/clang
-          sudo LN -s --force /usr/bin/ld.lld-$LLVM_VERSION /usr/bin/ld.lld
-          sudo LN -s --force /usr/bin/LLVM-objdump-$LLVM_VERSION /usr/bin/llvm-objdump
-          sudo LN -s --force /usr/bin/llvm-ar-$LLVM_VERSION /usr/bin/llvm-ar
-          sudo LN -s --force /usr/bin/LLVM-nm-$LLVM_VERSION /usr/bin/llvm-nm
-          sudo LN -s --force /usr/bin/llvm-strip-$LLVM_VERSION /usr/bin/llvm-strip
-          sudo LN -s --force /usr/bin/llvm-objcopy-$LLVM_VERSION /usr/bin/llvm-objcopy
-          sudo LN -s --force /usr/bin/llvm-readelf-$LLVM_VERSION /usr/bin/llvm-readelf
-          sudo LN -s --force /usr/bin/clang++-$LLVM_VERSION /usr/bin/clang++
-      - 名称：查看KernelSU
-        用途：行动/checkout@v5
-        与：
-          仓库：tiann/KernelSU
-          路径：KernelSU
-          取水深度：0
+  build:
+    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && !github.event.pull_request.draft)
 
-      - 名称：设置内核源代码
-        运行：|
-          git clone https://chromium.googlesource.com/chromiumos/third_party/kernel.git -b ${{ env.git_tag }} --depth=1
-          # === 以下两行为针对报错的修复 ===
-          echo "[+] 修复 X86_FEATURE_INDIRECT_SAFE 未定义报错"
-          echo "#define X86_FEATURE_INDIRECT_SAFE (18*32+25)" >> kernel/arch/x86/include/asm/cpufeatures.h
-          # ================================
+    strategy:
+      matrix:
+        include:
 
-      - 名称：从 Makefile 提取版本
-        工作目录：kernel
-        运行：|
-          VERSION=$（grep -E '^VERSION = ' Makefile | awk '{print $3}'）
-          PATCHLEVEL=$（grep -E '^PATCHLEVEL = ' Makefile | awk '{print $3}'）
-          SUBLEVEL=$（grep -E '^SUBLEVEL = ' Makefile | awk '{print $3}'）
-          echo “ChromeOS ARCVM Linux 内核版本：$VERSION.$PATCHLEVEL.$SUBLEVEL”
-          echo “version=$VERSION.$PATCHLEVEL.$SUBLEVEL” >> $GITHUB_ENV
-      - 名称：设置KernelSU
-        工作目录：kernel
-        运行：|
-          echo “[+] KernelSU 设置”
-          KERNEL_ROOT=$GITHUB_WORKSPACE/kernel
-          回声 “[+] KERNEL_ROOT： $KERNEL_ROOT”
-          echo “[+] 将 KernelSU 驱动复制到 $KERNEL_ROOT/drivers”
-          inn -sf $GITHUB_WORKSPACE/KernelSU/kernel $KERNEL_ROOT/drivers/kernelsu
-          echo “[+] 将 KernelSU 驱动添加到 Makefile”
-          DRIVER_MAKEFILE=$KERNEL_ROOT/drivers/Makefile
-          DRIVER_KCONFIG=$KERNEL_ROOT/drivers/Kconfig
-          grep -q “kernelsu” “$DRIVER_MAKEFILE” ||printf “\nobj-\$（CONFIG_KSU） += kernelsu/\n” >> “$DRIVER_MAKEFILE”
-          grep -q “kernelsu” “$DRIVER_KCONFIG” ||sed -i “/endmenu/i\\source \”drivers/kernelsu/Kconfig\“” “$DRIVER_KCONFIG”
-          echo “[+] 应用 KernelSU 补丁”
-          cd $KERNEL_ROOT && git apply $GITHUB_WORKSPACE/KernelSU/.github/patches/5.10/*.patch ||回声 “[-] 找不到补丁”
-          echo “[+] Patch script/setlocalversion”
-          sed -i 's/-dirty//g' $KERNEL_ROOT/scripts/setlocalversion
-          echo “[+] KernelSU 设置完成。”
-          cd $GITHUB_WORKSPACE/KernelSU
-          KSU_VERSION=$（（$（git rev-list --count HEAD） + 10200））
-          echo “KernelSU 版本： $KSU_VERSION”
-          echo “kernelsu_version=$KSU_VERSION” >> $GITHUB_ENV
-      - 名称：构建内核
-        工作目录：kernel
-        环境：
-          KERNEL_IMAGE_NAME： ${{ matrix.kernel_image_name }}
-          ARCHs： ${{ matrix.arch }}
-        运行：|
-          集合 -a && 。${{ matrix.build_config }};集合+a
-          export DEFCONFIG=${{ matrix.defconfig }}
-          如果 [ ！ -z ${{ vars.EXPECTED_SIZE }} ] & [ ！ -z ${{ vars.EXPECTED_HASH }} ];则
-          export KSU_EXPECTED_SIZE=${{ vars.EXPECTED_SIZE }}
-          export KSU_EXPECTED_HASH=${{ vars.EXPECTED_HASH }}
-          Fi
-          make LLVM=1 LLVM_IAS=1 DEPMOD=depmod DTC=dtc O=${PWD} mrproper
-          make LLVM=1 LLVM_IAS=1 DEPMOD=depmod DTC=dtc O=${PWD} ${DEFCONFIG} < /dev/null
-          scripts/config --file .config -e LTO_CLANG -d LTO_NONE -e LTO_CLANG_THIN -d LTO_CLANG_FULL -e THINLTO
-          make LLVM=1 LLVM_IAS=1 DEPMOD=depmod DTC=dtc O=${PWD} -j$（nproc） ${KERNEL_IMAGE_NAME} modules prepare-objtool
-          ls -l -h ${PWD}/arch/${ARCH}/boot
-          echo “file_path=${PWD}/arch/${ARCH}/boot/${KERNEL_IMAGE_NAME}” >> $GITHUB_ENV
-      - name： Upload kernel-ARCVM-${{ matrix.arch }}-${{ env.version }}
-        用途：动作/上传-artifact@v5
-        与：
-          name： kernel-ARCVM-${{ matrix.arch }}-${{ env.version }}
-          路径：“${{ env.file_path }}”
+          - ARCH: x86_64
+            kernel_image_name: bzImage
+            build_config: build.config.gki.x86_64
+            defconfig: x86_64_arcvm_defconfig
+
+          - ARCH: arm64
+            kernel_image_name: Image
+            build_config: build.config.gki.aarch64
+            defconfig: arm64_arcvm_defconfig
+
+
+    name: Build ChromeOS ARCVM Kernel ${{ matrix.ARCH }}
+
+    runs-on: ubuntu-22.04
+
+
+    env:
+      LTO: thin
+      ROOT_DIR: /
+      KERNEL_DIR: ${{ github.workspace }}/kernel
+
+
+    steps:
+
+
+    - name: Install dependencies
+      run: |
+
+        sudo apt update
+
+        sudo apt install -y \
+        bc \
+        bison \
+        build-essential \
+        ca-certificates \
+        flex \
+        git \
+        gnupg \
+        libelf-dev \
+        libssl-dev \
+        libncurses-dev \
+        binutils-aarch64-linux-gnu \
+        gcc-aarch64-linux-gnu \
+        gzip \
+        rsync \
+        python3 \
+        device-tree-compiler
+
+
+        sudo ln -sf python3 /usr/bin/python
+
+
+        export LLVM_VERSION=14
+
+
+        wget https://apt.llvm.org/llvm.sh
+
+        chmod +x llvm.sh
+
+        sudo ./llvm.sh $LLVM_VERSION
+
+        rm llvm.sh
+
+
+        for tool in clang clang++ ld.lld llvm-ar llvm-nm llvm-strip llvm-objcopy llvm-readelf llvm-objdump
+        do
+          sudo ln -sf /usr/bin/${tool}-${LLVM_VERSION} /usr/bin/${tool}
+        done
+
+
+
+    - name: Checkout KernelSU
+
+      uses: actions/checkout@v5
+
+      with:
+
+        repository: tiann/KernelSU
+
+        path: KernelSU
+
+        fetch-depth: 0
+
+
+
+    - name: Clone ChromeOS kernel
+
+      run: |
+
+        git clone \
+        https://chromium.googlesource.com/chromiumos/third_party/kernel.git \
+        -b ${{ env.git_tag }} \
+        --depth=1 \
+        kernel
+
+
+
+    - name: Kernel version
+
+      working-directory: kernel
+
+      run: |
+
+        VERSION=$(grep '^VERSION =' Makefile | awk '{print $3}')
+
+        PATCHLEVEL=$(grep '^PATCHLEVEL =' Makefile | awk '{print $3}')
+
+        SUBLEVEL=$(grep '^SUBLEVEL =' Makefile | awk '{print $3}')
+
+
+        echo "Linux version $VERSION.$PATCHLEVEL.$SUBLEVEL"
+
+        echo "version=$VERSION.$PATCHLEVEL.$SUBLEVEL" >> $GITHUB_ENV
+
+
+
+    - name: Integrate KernelSU
+
+      working-directory: kernel
+
+      run: |
+
+        echo "[+] Installing KernelSU"
+
+
+        KERNEL_ROOT=$GITHUB_WORKSPACE/kernel
+
+
+        mkdir -p \
+        $KERNEL_ROOT/drivers/kernelsu
+
+
+        cp -r \
+        $GITHUB_WORKSPACE/KernelSU/kernel/* \
+        $KERNEL_ROOT/drivers/kernelsu/
+
+
+        echo "[+] Add Makefile"
+
+
+        grep -q kernelsu drivers/Makefile || \
+        echo 'obj-$(CONFIG_KSU) += kernelsu/' >> drivers/Makefile
+
+
+
+        echo "[+] Add Kconfig"
+
+
+        grep -q kernelsu drivers/Kconfig || \
+        sed -i '/endmenu/i source "drivers/kernelsu/Kconfig"' drivers/Kconfig
+
+
+
+        echo "[+] Fix ChromeOS missing X86_FEATURE_INDIRECT_SAFE"
+
+
+        FILE=$KERNEL_ROOT/drivers/kernelsu/core/init.c
+
+
+        sed -i \
+        's/boot_cpu_has(X86_FEATURE_INDIRECT_SAFE)/0/g' \
+        $FILE
+
+
+
+        echo "[+] Remove dirty suffix"
+
+
+        sed -i 's/-dirty//g' \
+        scripts/setlocalversion
+
+
+
+        echo "[+] KernelSU done"
+
+
+
+    - name: Build kernel
+
+      working-directory: kernel
+
+      env:
+
+        KERNEL_IMAGE_NAME: ${{ matrix.kernel_image_name }}
+
+        ARCH: ${{ matrix.ARCH }}
+
+
+      run: |
+
+
+        set -e
+
+
+
+        set -a
+
+        source ${{ matrix.build_config }}
+
+        set +a
+
+
+
+        export DEFCONFIG=${{ matrix.defconfig }}
+
+
+
+        make \
+        LLVM=1 \
+        LLVM_IAS=1 \
+        DEPMOD=depmod \
+        DTC=dtc \
+        O=${PWD} \
+        mrproper
+
+
+
+        make \
+        LLVM=1 \
+        LLVM_IAS=1 \
+        DEPMOD=depmod \
+        DTC=dtc \
+        O=${PWD} \
+        ${DEFCONFIG}
+
+
+
+        scripts/config \
+        --file .config \
+        -e LTO_CLANG \
+        -d LTO_NONE \
+        -e LTO_CLANG_THIN \
+        -d LTO_CLANG_FULL \
+        -e KSU
+
+
+
+        make \
+        LLVM=1 \
+        LLVM_IAS=1 \
+        DEPMOD=depmod \
+        DTC=dtc \
+        O=${PWD} \
+        -j$(nproc) \
+        ${KERNEL_IMAGE_NAME} \
+        modules \
+        prepare-objtool
+
+
+
+        ls -lh \
+        arch/${ARCH}/boot
+
+
+
+        echo \
+        "file_path=${PWD}/arch/${ARCH}/boot/${KERNEL_IMAGE_NAME}" \
+        >> $GITHUB_ENV
+
+
+
+    - name: Upload kernel
+
+      uses: actions/upload-artifact@v5
+
+      with:
+
+        name: kernel-ARCVM-${{ matrix.ARCH }}-${{ env.version }}
+
+        path: ${{ env.file_path }}
